#!/usr/bin/env bash
set -Eeuo pipefail

usage() {
    cat <<'USAGE'
Create a protected, Git-ignored local copy of the active Push SDK credentials.

Usage:
  HIKVISION_DEVICE_ADMIN_PASSWORD=... \
    scripts/sync-pushsdk-local-secrets.sh [options]

Options:
  --host SSH_TARGET       SSH target for the production VPS (default: aruvo-vps).
  --deploy-user USER      VPS user that owns the production secrets (default: abdullah).
  --device-address IP     Terminal management address (default: 10.203.216.162).
  --device-admin USER     Terminal management username (default: admin).
  -h, --help              Show this help text.

The command writes .local-secrets/attendance-pushsdk-production.env with mode
600. It contains the terminal Push SDK password, Laravel gateway token, Laravel
APP_KEY, and the supplied terminal management credential. It never prints a
secret and the destination is ignored by Git.
USAGE
}

ssh_target="${ARUVO_SSH_TARGET:-aruvo-vps}"
deploy_user="${ARUVO_DEPLOY_USER:-abdullah}"
device_address="${HIKVISION_DEVICE_ADDRESS:-10.203.216.162}"
device_admin="${HIKVISION_DEVICE_ADMIN_USERNAME:-admin}"

require_value() {
    [ "$#" -ge 2 ] || {
        echo "$1 requires a value." >&2
        exit 2
    }
}

while [ "$#" -gt 0 ]; do
    case "$1" in
        --host)
            require_value "$@"
            ssh_target="$2"
            shift 2
            ;;
        --deploy-user)
            require_value "$@"
            deploy_user="$2"
            shift 2
            ;;
        --device-address)
            require_value "$@"
            device_address="$2"
            shift 2
            ;;
        --device-admin)
            require_value "$@"
            device_admin="$2"
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Unknown argument: $1" >&2
            usage >&2
            exit 2
            ;;
    esac
done

: "${HIKVISION_DEVICE_ADMIN_PASSWORD:?Set HIKVISION_DEVICE_ADMIN_PASSWORD only for this command.}"

is_safe_remote_argument() {
    [[ "$1" =~ ^[A-Za-z0-9._/@:+,=-]+$ ]]
}

for value in "$deploy_user"; do
    if ! is_safe_remote_argument "$value"; then
        echo "Unsupported character in a remote argument: $value" >&2
        exit 2
    fi
done

repository_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)"
secret_directory="$repository_root/.local-secrets"
secret_file="$secret_directory/attendance-pushsdk-production.env"

git -C "$repository_root" check-ignore -q -- .local-secrets/attendance-pushsdk-production.env \
    || { echo "Refusing to write a destination that is not ignored by Git." >&2; exit 1; }

umask 077
install -d -m 700 "$secret_directory"
temporary_file="$(mktemp "$secret_directory/.attendance-pushsdk-production.XXXXXX")"
cleanup() {
    rm -f -- "$temporary_file"
}
trap cleanup EXIT

remote_values="$temporary_file.remote"
trap 'rm -f -- "$temporary_file" "$remote_values"' EXIT

# Values are base64 encoded only for safe transport through the line-oriented
# SSH response. The resulting local file remains plaintext but mode 600.
ssh -- "$ssh_target" bash -s -- "$deploy_user" > "$remote_values" <<'REMOTE_SCRIPT'
#!/usr/bin/env bash
set -Eeuo pipefail

deploy_user="$1"
gateway_env="/home/$deploy_user/services/secrets/attendance-pushsdk/gateway/runtime.env"
receiver_env="/home/$deploy_user/services/secrets/attendance-pushsdk/receiver/runtime.env"

read_env_value() {
    local path="$1"
    local key="$2"
    local value
    value="$(awk -v key="$key" 'index($0, key "=") == 1 { print substr($0, length(key) + 2); exit }' "$path")"
    [ -n "$value" ] || {
        echo "Production secret '$key' is missing from $path." >&2
        exit 1
    }
    printf '%s=%s\n' "$key" "$(printf '%s' "$value" | base64 | tr -d '\n')"
}

[ -r "$gateway_env" ] || { echo "Gateway runtime environment is not readable." >&2; exit 1; }
[ -r "$receiver_env" ] || { echo "Receiver runtime environment is not readable." >&2; exit 1; }

read_env_value "$gateway_env" PUSHSDK_TERMINAL_PASSWORD
read_env_value "$gateway_env" ATTENDANCE_PUSH_GATEWAY_TOKEN
read_env_value "$receiver_env" APP_KEY
REMOTE_SCRIPT

{
    printf '%s\n' '# Local workstation credentials for the production Push SDK deployment.'
    printf '%s\n' '# Generated by scripts/sync-pushsdk-local-secrets.sh; never commit this file.'
    printf 'HIKVISION_DEVICE_ADDRESS=%q\n' "$device_address"
    printf 'HIKVISION_DEVICE_ADMIN_USERNAME=%q\n' "$device_admin"
    printf 'HIKVISION_DEVICE_ADMIN_PASSWORD=%q\n' "$HIKVISION_DEVICE_ADMIN_PASSWORD"

    while IFS='=' read -r name encoded_value; do
        case "$name" in
            PUSHSDK_TERMINAL_PASSWORD|ATTENDANCE_PUSH_GATEWAY_TOKEN|APP_KEY)
                ;;
            *)
                echo "Unexpected secret name received from the VPS: $name" >&2
                exit 1
                ;;
        esac
        value="$(printf '%s' "$encoded_value" | base64 --decode)"
        [ -n "$value" ] || {
            echo "VPS returned an empty value for $name." >&2
            exit 1
        }
        printf '%s=%q\n' "$name" "$value"
    done < "$remote_values"
} > "$temporary_file"

chmod 600 "$temporary_file"
mv -f -- "$temporary_file" "$secret_file"
rm -f -- "$remote_values"
trap - EXIT

printf 'Stored protected Push SDK credentials in %s (mode %s).\n' \
    "$secret_file" "$(stat --format '%a' "$secret_file")"
